export enum APIs {
  GET_OVERVIEW_EVENT = '/events',
}

export enum ErrorCode {
  ERR = 'ERR',
  ERR_SOCKET = 'ERR_SOCKET',
  ERR_SOCKET_DEVICE_NOTFOUND = 'ERR_SOCKET_DEVICE_NOTFOUND',
  ERR_VIRUS = 'ERR_VIRUS',
  ERR_EXCEED_THRESHOLD = 'ERR_EXCEED_THRESHOLD',
  ERR_NETWORK = 'ERR_NETWORK',
  ERR_CANCELED = 'ERR_CANCELED',
}
